// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Mqmz4Z7HEonUgGaH_GJNvMrlYhWfU1M',
    appId: '1:1072953170013:web:78ec7a5e6a9e8be14095b4',
    messagingSenderId: '1072953170013',
    projectId: 'uni-tool-app',
    authDomain: 'uni-tool-app.firebaseapp.com',
    databaseURL: 'https://uni-tool-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uni-tool-app.firebasestorage.app',
    measurementId: 'G-QTRTCX7F65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTF76EULNuXQ_U7eY_rEz5ZREofsnyE_U',
    appId: '1:1072953170013:android:cdd62a2b34b3aac54095b4',
    messagingSenderId: '1072953170013',
    projectId: 'uni-tool-app',
    databaseURL: 'https://uni-tool-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uni-tool-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYe8944WC0Zq9lv1qcJaZUVyhKbu9bfE0',
    appId: '1:1072953170013:ios:02a8c96379d4e2134095b4',
    messagingSenderId: '1072953170013',
    projectId: 'uni-tool-app',
    databaseURL: 'https://uni-tool-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uni-tool-app.firebasestorage.app',
    iosBundleId: 'com.example.unitools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYe8944WC0Zq9lv1qcJaZUVyhKbu9bfE0',
    appId: '1:1072953170013:ios:02a8c96379d4e2134095b4',
    messagingSenderId: '1072953170013',
    projectId: 'uni-tool-app',
    databaseURL: 'https://uni-tool-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uni-tool-app.firebasestorage.app',
    iosBundleId: 'com.example.unitools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Mqmz4Z7HEonUgGaH_GJNvMrlYhWfU1M',
    appId: '1:1072953170013:web:c9dbe1118bc84c004095b4',
    messagingSenderId: '1072953170013',
    projectId: 'uni-tool-app',
    authDomain: 'uni-tool-app.firebaseapp.com',
    databaseURL: 'https://uni-tool-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uni-tool-app.firebasestorage.app',
    measurementId: 'G-VZX7PX91SW',
  );

}